# Server
server.port=${PORT:8080}

# Base de datos (Limitado a 2 conexiones para no saturar Supabase)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.yowhjhvtesevurqbzpqd&password=Qrj1FhxPYRVlu4Jk}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:BarberiaSecretKeyForJWTTokenGeneration1234567890ABC}
jwt.expirationMs=${JWT_EXPIRATION_MS:86400000}

# Twilio
twilio.account.sid=${TWILIO_ACCOUNT_SID:TU_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN:TU_AUTH_TOKEN}
twilio.whatsapp.from=${TWILIO_WHATSAPP_FROM:whatsapp:+14155238886}

# Config
spring.main.allow-circular-references=true

# Springdoc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true